// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

type DevicePairingKinds uint32

const SignatureDevicePairingKinds string = "enum(Windows.Devices.Enumeration.DevicePairingKinds;u4)"

const (
	DevicePairingKindsNone                      DevicePairingKinds = 0
	DevicePairingKindsConfirmOnly               DevicePairingKinds = 1
	DevicePairingKindsDisplayPin                DevicePairingKinds = 2
	DevicePairingKindsProvidePin                DevicePairingKinds = 4
	DevicePairingKindsConfirmPinMatch           DevicePairingKinds = 8
	DevicePairingKindsProvidePasswordCredential DevicePairingKinds = 16
)
