// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

type DevicePairingResultStatus int32

const SignatureDevicePairingResultStatus string = "enum(Windows.Devices.Enumeration.DevicePairingResultStatus;i4)"

const (
	DevicePairingResultStatusPaired                       DevicePairingResultStatus = 0
	DevicePairingResultStatusNotReadyToPair               DevicePairingResultStatus = 1
	DevicePairingResultStatusNotPaired                    DevicePairingResultStatus = 2
	DevicePairingResultStatusAlreadyPaired                DevicePairingResultStatus = 3
	DevicePairingResultStatusConnectionRejected           DevicePairingResultStatus = 4
	DevicePairingResultStatusTooManyConnections           DevicePairingResultStatus = 5
	DevicePairingResultStatusHardwareFailure              DevicePairingResultStatus = 6
	DevicePairingResultStatusAuthenticationTimeout        DevicePairingResultStatus = 7
	DevicePairingResultStatusAuthenticationNotAllowed     DevicePairingResultStatus = 8
	DevicePairingResultStatusAuthenticationFailure        DevicePairingResultStatus = 9
	DevicePairingResultStatusNoSupportedProfiles          DevicePairingResultStatus = 10
	DevicePairingResultStatusProtectionLevelCouldNotBeMet DevicePairingResultStatus = 11
	DevicePairingResultStatusAccessDenied                 DevicePairingResultStatus = 12
	DevicePairingResultStatusInvalidCeremonyData          DevicePairingResultStatus = 13
	DevicePairingResultStatusPairingCanceled              DevicePairingResultStatus = 14
	DevicePairingResultStatusOperationAlreadyInProgress   DevicePairingResultStatus = 15
	DevicePairingResultStatusRequiredHandlerNotRegistered DevicePairingResultStatus = 16
	DevicePairingResultStatusRejectedByHandler            DevicePairingResultStatus = 17
	DevicePairingResultStatusRemoteDeviceHasAssociation   DevicePairingResultStatus = 18
	DevicePairingResultStatusFailed                       DevicePairingResultStatus = 19
)
