// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

type DeviceUnpairingResultStatus int32

const SignatureDeviceUnpairingResultStatus string = "enum(Windows.Devices.Enumeration.DeviceUnpairingResultStatus;i4)"

const (
	DeviceUnpairingResultStatusUnpaired                   DeviceUnpairingResultStatus = 0
	DeviceUnpairingResultStatusAlreadyUnpaired            DeviceUnpairingResultStatus = 1
	DeviceUnpairingResultStatusOperationAlreadyInProgress DeviceUnpairingResultStatus = 2
	DeviceUnpairingResultStatusAccessDenied               DeviceUnpairingResultStatus = 3
	DeviceUnpairingResultStatusFailed                     DeviceUnpairingResultStatus = 4
)
