// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureDevicePairingResult string = "rc(Windows.Devices.Enumeration.DevicePairingResult;{072b02bf-dd95-4025-9b37-de51adba37b7})"

type DevicePairingResult struct {
	ole.IUnknown
}

func (impl *DevicePairingResult) GetStatus() (DevicePairingResultStatus, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingResult))
	defer itf.Release()
	v := (*iDevicePairingResult)(unsafe.Pointer(itf))
	return v.GetStatus()
}

func (impl *DevicePairingResult) GetProtectionLevelUsed() (DevicePairingProtectionLevel, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingResult))
	defer itf.Release()
	v := (*iDevicePairingResult)(unsafe.Pointer(itf))
	return v.GetProtectionLevelUsed()
}

const GUIDiDevicePairingResult string = "072b02bf-dd95-4025-9b37-de51adba37b7"
const SignatureiDevicePairingResult string = "{072b02bf-dd95-4025-9b37-de51adba37b7}"

type iDevicePairingResult struct {
	ole.IInspectable
}

type iDevicePairingResultVtbl struct {
	ole.IInspectableVtbl

	GetStatus              uintptr
	GetProtectionLevelUsed uintptr
}

func (v *iDevicePairingResult) VTable() *iDevicePairingResultVtbl {
	return (*iDevicePairingResultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDevicePairingResult) GetStatus() (DevicePairingResultStatus, error) {
	var out DevicePairingResultStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DevicePairingResultStatus
	)

	if hr != 0 {
		return DevicePairingResultStatusPaired, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDevicePairingResult) GetProtectionLevelUsed() (DevicePairingProtectionLevel, error) {
	var out DevicePairingProtectionLevel
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProtectionLevelUsed,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DevicePairingProtectionLevel
	)

	if hr != 0 {
		return DevicePairingProtectionLevelDefault, ole.NewError(hr)
	}

	return out, nil
}
