// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureDeviceUnpairingResult string = "rc(Windows.Devices.Enumeration.DeviceUnpairingResult;{66f44ad3-79d9-444b-92cf-a92ef72571c7})"

type DeviceUnpairingResult struct {
	ole.IUnknown
}

func (impl *DeviceUnpairingResult) GetStatus() (DeviceUnpairingResultStatus, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceUnpairingResult))
	defer itf.Release()
	v := (*iDeviceUnpairingResult)(unsafe.Pointer(itf))
	return v.GetStatus()
}

const GUIDiDeviceUnpairingResult string = "66f44ad3-79d9-444b-92cf-a92ef72571c7"
const SignatureiDeviceUnpairingResult string = "{66f44ad3-79d9-444b-92cf-a92ef72571c7}"

type iDeviceUnpairingResult struct {
	ole.IInspectable
}

type iDeviceUnpairingResultVtbl struct {
	ole.IInspectableVtbl

	GetStatus uintptr
}

func (v *iDeviceUnpairingResult) VTable() *iDeviceUnpairingResultVtbl {
	return (*iDeviceUnpairingResultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDeviceUnpairingResult) GetStatus() (DeviceUnpairingResultStatus, error) {
	var out DeviceUnpairingResultStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DeviceUnpairingResultStatus
	)

	if hr != 0 {
		return DeviceUnpairingResultStatusUnpaired, ole.NewError(hr)
	}

	return out, nil
}
