// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureDevicePairingRequestedEventArgs string = "rc(Windows.Devices.Enumeration.DevicePairingRequestedEventArgs;{f717fc56-de6b-487f-8376-0180aca69963})"

type DevicePairingRequestedEventArgs struct {
	ole.IUnknown
}

func (impl *DevicePairingRequestedEventArgs) GetDeviceInformation() (*DeviceInformation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingRequestedEventArgs))
	defer itf.Release()
	v := (*iDevicePairingRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetDeviceInformation()
}

func (impl *DevicePairingRequestedEventArgs) GetPairingKind() (DevicePairingKinds, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingRequestedEventArgs))
	defer itf.Release()
	v := (*iDevicePairingRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetPairingKind()
}

func (impl *DevicePairingRequestedEventArgs) GetPin() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingRequestedEventArgs))
	defer itf.Release()
	v := (*iDevicePairingRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetPin()
}

func (impl *DevicePairingRequestedEventArgs) Accept() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingRequestedEventArgs))
	defer itf.Release()
	v := (*iDevicePairingRequestedEventArgs)(unsafe.Pointer(itf))
	return v.Accept()
}

func (impl *DevicePairingRequestedEventArgs) AcceptWithPin(pin string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingRequestedEventArgs))
	defer itf.Release()
	v := (*iDevicePairingRequestedEventArgs)(unsafe.Pointer(itf))
	return v.AcceptWithPin(pin)
}

func (impl *DevicePairingRequestedEventArgs) GetDeferral() (*foundation.Deferral, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDevicePairingRequestedEventArgs))
	defer itf.Release()
	v := (*iDevicePairingRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetDeferral()
}

const GUIDiDevicePairingRequestedEventArgs string = "f717fc56-de6b-487f-8376-0180aca69963"
const SignatureiDevicePairingRequestedEventArgs string = "{f717fc56-de6b-487f-8376-0180aca69963}"

type iDevicePairingRequestedEventArgs struct {
	ole.IInspectable
}

type iDevicePairingRequestedEventArgsVtbl struct {
	ole.IInspectableVtbl

	GetDeviceInformation uintptr
	GetPairingKind       uintptr
	GetPin               uintptr
	Accept               uintptr
	AcceptWithPin        uintptr
	GetDeferral          uintptr
}

func (v *iDevicePairingRequestedEventArgs) VTable() *iDevicePairingRequestedEventArgsVtbl {
	return (*iDevicePairingRequestedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDevicePairingRequestedEventArgs) GetDeviceInformation() (*DeviceInformation, error) {
	var out *DeviceInformation
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDeviceInformation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DeviceInformation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDevicePairingRequestedEventArgs) GetPairingKind() (DevicePairingKinds, error) {
	var out DevicePairingKinds
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPairingKind,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DevicePairingKinds
	)

	if hr != 0 {
		return DevicePairingKindsNone, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDevicePairingRequestedEventArgs) GetPin() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPin,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iDevicePairingRequestedEventArgs) Accept() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Accept,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDevicePairingRequestedEventArgs) AcceptWithPin(pin string) error {
	pinHStr, err := ole.NewHString(pin)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().AcceptWithPin,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(pinHStr),           // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDevicePairingRequestedEventArgs) GetDeferral() (*foundation.Deferral, error) {
	var out *foundation.Deferral
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDeferral,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.Deferral
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiDevicePairingRequestedEventArgs2 string = "c83752d9-e4d3-4db0-a360-a105e437dbdc"
const SignatureiDevicePairingRequestedEventArgs2 string = "{c83752d9-e4d3-4db0-a360-a105e437dbdc}"

type iDevicePairingRequestedEventArgs2 struct {
	ole.IInspectable
}

type iDevicePairingRequestedEventArgs2Vtbl struct {
	ole.IInspectableVtbl

	AcceptWithPasswordCredential uintptr
}

func (v *iDevicePairingRequestedEventArgs2) VTable() *iDevicePairingRequestedEventArgs2Vtbl {
	return (*iDevicePairingRequestedEventArgs2Vtbl)(unsafe.Pointer(v.RawVTable))
}
