// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

type DeviceWatcherStatus int32

const SignatureDeviceWatcherStatus string = "enum(Windows.Devices.Enumeration.DeviceWatcherStatus;i4)"

const (
	DeviceWatcherStatusCreated              DeviceWatcherStatus = 0
	DeviceWatcherStatusStarted              DeviceWatcherStatus = 1
	DeviceWatcherStatusEnumerationCompleted DeviceWatcherStatus = 2
	DeviceWatcherStatusStopping             DeviceWatcherStatus = 3
	DeviceWatcherStatusStopped              DeviceWatcherStatus = 4
	DeviceWatcherStatusAborted              DeviceWatcherStatus = 5
)
