// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

type DeviceInformationKind int32

const SignatureDeviceInformationKind string = "enum(Windows.Devices.Enumeration.DeviceInformationKind;i4)"

const (
	DeviceInformationKindUnknown                      DeviceInformationKind = 0
	DeviceInformationKindDeviceInterface              DeviceInformationKind = 1
	DeviceInformationKindDeviceContainer              DeviceInformationKind = 2
	DeviceInformationKindDevice                       DeviceInformationKind = 3
	DeviceInformationKindDeviceInterfaceClass         DeviceInformationKind = 4
	DeviceInformationKindAssociationEndpoint          DeviceInformationKind = 5
	DeviceInformationKindAssociationEndpointContainer DeviceInformationKind = 6
	DeviceInformationKindAssociationEndpointService   DeviceInformationKind = 7
	DeviceInformationKindDevicePanel                  DeviceInformationKind = 8
)
