// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

type DevicePairingProtectionLevel int32

const SignatureDevicePairingProtectionLevel string = "enum(Windows.Devices.Enumeration.DevicePairingProtectionLevel;i4)"

const (
	DevicePairingProtectionLevelDefault                     DevicePairingProtectionLevel = 0
	DevicePairingProtectionLevelNone                        DevicePairingProtectionLevel = 1
	DevicePairingProtectionLevelEncryption                  DevicePairingProtectionLevel = 2
	DevicePairingProtectionLevelEncryptionAndAuthentication DevicePairingProtectionLevel = 3
)
