// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
)

const SignatureDeviceInformationUpdate string = "rc(Windows.Devices.Enumeration.DeviceInformationUpdate;{8f315305-d972-44b7-a37e-9e822c78213b})"

type DeviceInformationUpdate struct {
	ole.IUnknown
}

func (impl *DeviceInformationUpdate) GetId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceInformationUpdate))
	defer itf.Release()
	v := (*iDeviceInformationUpdate)(unsafe.Pointer(itf))
	return v.GetId()
}

func (impl *DeviceInformationUpdate) GetProperties() (*collections.IMapView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceInformationUpdate))
	defer itf.Release()
	v := (*iDeviceInformationUpdate)(unsafe.Pointer(itf))
	return v.GetProperties()
}

const GUIDiDeviceInformationUpdate string = "8f315305-d972-44b7-a37e-9e822c78213b"
const SignatureiDeviceInformationUpdate string = "{8f315305-d972-44b7-a37e-9e822c78213b}"

type iDeviceInformationUpdate struct {
	ole.IInspectable
}

type iDeviceInformationUpdateVtbl struct {
	ole.IInspectableVtbl

	GetId         uintptr
	GetProperties uintptr
}

func (v *iDeviceInformationUpdate) VTable() *iDeviceInformationUpdateVtbl {
	return (*iDeviceInformationUpdateVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDeviceInformationUpdate) GetId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iDeviceInformationUpdate) GetProperties() (*collections.IMapView, error) {
	var out *collections.IMapView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProperties,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IMapView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiDeviceInformationUpdate2 string = "5d9d148c-a873-485e-baa6-aa620788e3cc"
const SignatureiDeviceInformationUpdate2 string = "{5d9d148c-a873-485e-baa6-aa620788e3cc}"

type iDeviceInformationUpdate2 struct {
	ole.IInspectable
}

type iDeviceInformationUpdate2Vtbl struct {
	ole.IInspectableVtbl

	GetKind uintptr
}

func (v *iDeviceInformationUpdate2) VTable() *iDeviceInformationUpdate2Vtbl {
	return (*iDeviceInformationUpdate2Vtbl)(unsafe.Pointer(v.RawVTable))
}
