// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package enumeration

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureDeviceWatcher string = "rc(Windows.Devices.Enumeration.DeviceWatcher;{c9eab97d-8f6b-4f96-a9f4-abc814e22271})"

type DeviceWatcher struct {
	ole.IUnknown
}

func (impl *DeviceWatcher) AddAdded(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.AddAdded(handler)
}

func (impl *DeviceWatcher) RemoveAdded(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.RemoveAdded(token)
}

func (impl *DeviceWatcher) AddUpdated(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.AddUpdated(handler)
}

func (impl *DeviceWatcher) RemoveUpdated(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.RemoveUpdated(token)
}

func (impl *DeviceWatcher) AddRemoved(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.AddRemoved(handler)
}

func (impl *DeviceWatcher) RemoveRemoved(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.RemoveRemoved(token)
}

func (impl *DeviceWatcher) AddEnumerationCompleted(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.AddEnumerationCompleted(handler)
}

func (impl *DeviceWatcher) RemoveEnumerationCompleted(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.RemoveEnumerationCompleted(token)
}

func (impl *DeviceWatcher) AddStopped(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.AddStopped(handler)
}

func (impl *DeviceWatcher) RemoveStopped(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.RemoveStopped(token)
}

func (impl *DeviceWatcher) GetStatus() (DeviceWatcherStatus, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.GetStatus()
}

func (impl *DeviceWatcher) Start() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.Start()
}

func (impl *DeviceWatcher) Stop() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDeviceWatcher))
	defer itf.Release()
	v := (*iDeviceWatcher)(unsafe.Pointer(itf))
	return v.Stop()
}

const GUIDiDeviceWatcher string = "c9eab97d-8f6b-4f96-a9f4-abc814e22271"
const SignatureiDeviceWatcher string = "{c9eab97d-8f6b-4f96-a9f4-abc814e22271}"

type iDeviceWatcher struct {
	ole.IInspectable
}

type iDeviceWatcherVtbl struct {
	ole.IInspectableVtbl

	AddAdded                   uintptr
	RemoveAdded                uintptr
	AddUpdated                 uintptr
	RemoveUpdated              uintptr
	AddRemoved                 uintptr
	RemoveRemoved              uintptr
	AddEnumerationCompleted    uintptr
	RemoveEnumerationCompleted uintptr
	AddStopped                 uintptr
	RemoveStopped              uintptr
	GetStatus                  uintptr
	Start                      uintptr
	Stop                       uintptr
}

func (v *iDeviceWatcher) VTable() *iDeviceWatcherVtbl {
	return (*iDeviceWatcherVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDeviceWatcher) AddAdded(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddAdded,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDeviceWatcher) RemoveAdded(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveAdded,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDeviceWatcher) AddUpdated(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddUpdated,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDeviceWatcher) RemoveUpdated(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveUpdated,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDeviceWatcher) AddRemoved(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddRemoved,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDeviceWatcher) RemoveRemoved(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveRemoved,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDeviceWatcher) AddEnumerationCompleted(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddEnumerationCompleted,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDeviceWatcher) RemoveEnumerationCompleted(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveEnumerationCompleted,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDeviceWatcher) AddStopped(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddStopped,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDeviceWatcher) RemoveStopped(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveStopped,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDeviceWatcher) GetStatus() (DeviceWatcherStatus, error) {
	var out DeviceWatcherStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DeviceWatcherStatus
	)

	if hr != 0 {
		return DeviceWatcherStatusCreated, ole.NewError(hr)
	}

	return out, nil
}

func (v *iDeviceWatcher) Start() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Start,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iDeviceWatcher) Stop() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Stop,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiDeviceWatcher2 string = "ff08456e-ed14-49e9-9a69-8117c54ae971"
const SignatureiDeviceWatcher2 string = "{ff08456e-ed14-49e9-9a69-8117c54ae971}"

type iDeviceWatcher2 struct {
	ole.IInspectable
}

type iDeviceWatcher2Vtbl struct {
	ole.IInspectableVtbl

	GetBackgroundTrigger uintptr
}

func (v *iDeviceWatcher2) VTable() *iDeviceWatcher2Vtbl {
	return (*iDeviceWatcher2Vtbl)(unsafe.Pointer(v.RawVTable))
}
