// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"github.com/go-ole/go-ole"
)

const SignatureDataReaderLoadOperation string = "rc(Windows.Storage.Streams.DataReaderLoadOperation;{00000036-0000-0000-c000-000000000046})"

type DataReaderLoadOperation struct {
	ole.IUnknown
}
