// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const GUIDIRandomAccessStreamWithContentType string = "cc254827-4b3d-438f-9232-10c76bc7e038"
const SignatureIRandomAccessStreamWithContentType string = "{cc254827-4b3d-438f-9232-10c76bc7e038}"

type IRandomAccessStreamWithContentType struct {
	ole.IInspectable
}

type IRandomAccessStreamWithContentTypeVtbl struct {
	ole.IInspectableVtbl
}

func (v *IRandomAccessStreamWithContentType) VTable() *IRandomAccessStreamWithContentTypeVtbl {
	return (*IRandomAccessStreamWithContentTypeVtbl)(unsafe.Pointer(v.RawVTable))
}
