// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package imaging

import (
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/storage/streams"
)

const SignatureImageStream string = "rc(Windows.Graphics.Imaging.ImageStream;{cc254827-4b3d-438f-9232-10c76bc7e038})"

type ImageStream struct {
	ole.IUnknown
}

func (impl *ImageStream) GetContentType() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIContentTypeProvider))
	defer itf.Release()
	v := (*streams.IContentTypeProvider)(unsafe.Pointer(itf))
	return v.GetContentType()
}

func (impl *ImageStream) GetSize() (uint64, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetSize()
}

func (impl *ImageStream) SetSize(value uint64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.SetSize(value)
}

func (impl *ImageStream) GetInputStreamAt(position uint64) (*IInputStream, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetInputStreamAt(position)
}

func (impl *ImageStream) GetOutputStreamAt(position uint64) (*IOutputStream, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetOutputStreamAt(position)
}

func (impl *ImageStream) GetPosition() (uint64, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetPosition()
}

func (impl *ImageStream) Seek(position uint64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.Seek(position)
}

func (impl *ImageStream) CloneStream() (*IRandomAccessStream, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.CloneStream()
}

func (impl *ImageStream) GetCanRead() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetCanRead()
}

func (impl *ImageStream) GetCanWrite() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*streams.IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetCanWrite()
}

func (impl *ImageStream) WriteAsync(buffer *IBuffer) (*foundation.IAsyncOperationWithProgress, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIOutputStream))
	defer itf.Release()
	v := (*streams.IOutputStream)(unsafe.Pointer(itf))
	return v.WriteAsync(buffer)
}

func (impl *ImageStream) FlushAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIOutputStream))
	defer itf.Release()
	v := (*streams.IOutputStream)(unsafe.Pointer(itf))
	return v.FlushAsync()
}

func (impl *ImageStream) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

func (impl *ImageStream) ReadAsync(buffer *IBuffer, count uint32, options InputStreamOptions) (*foundation.IAsyncOperationWithProgress, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(streams.GUIDIInputStream))
	defer itf.Release()
	v := (*streams.IInputStream)(unsafe.Pointer(itf))
	return v.ReadAsync(buffer, count, options)
}
