// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package radios

type RadioAccessStatus int32

const SignatureRadioAccessStatus string = "enum(Windows.Devices.Radios.RadioAccessStatus;i4)"

const (
	RadioAccessStatusUnspecified    RadioAccessStatus = 0
	RadioAccessStatusAllowed        RadioAccessStatus = 1
	RadioAccessStatusDeniedByUser   RadioAccessStatus = 2
	RadioAccessStatusDeniedBySystem RadioAccessStatus = 3
)
