// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package radios

type RadioKind int32

const SignatureRadioKind string = "enum(Windows.Devices.Radios.RadioKind;i4)"

const (
	RadioKindOther           RadioKind = 0
	RadioKindWiFi            RadioKind = 1
	RadioKindMobileBroadband RadioKind = 2
	RadioKindBluetooth       RadioKind = 3
	RadioKindFM              RadioKind = 4
)
