// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package radios

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureRadio string = "rc(Windows.Devices.Radios.Radio;{252118df-b33e-416a-875f-1cf38ae2d83e})"

type Radio struct {
	ole.IUnknown
}

func (impl *Radio) SetStateAsync(value RadioState) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiRadio))
	defer itf.Release()
	v := (*iRadio)(unsafe.Pointer(itf))
	return v.SetStateAsync(value)
}

func (impl *Radio) AddStateChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiRadio))
	defer itf.Release()
	v := (*iRadio)(unsafe.Pointer(itf))
	return v.AddStateChanged(handler)
}

func (impl *Radio) RemoveStateChanged(eventCookie foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiRadio))
	defer itf.Release()
	v := (*iRadio)(unsafe.Pointer(itf))
	return v.RemoveStateChanged(eventCookie)
}

func (impl *Radio) GetState() (RadioState, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiRadio))
	defer itf.Release()
	v := (*iRadio)(unsafe.Pointer(itf))
	return v.GetState()
}

func (impl *Radio) GetName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiRadio))
	defer itf.Release()
	v := (*iRadio)(unsafe.Pointer(itf))
	return v.GetName()
}

func (impl *Radio) GetKind() (RadioKind, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiRadio))
	defer itf.Release()
	v := (*iRadio)(unsafe.Pointer(itf))
	return v.GetKind()
}

const GUIDiRadio string = "252118df-b33e-416a-875f-1cf38ae2d83e"
const SignatureiRadio string = "{252118df-b33e-416a-875f-1cf38ae2d83e}"

type iRadio struct {
	ole.IInspectable
}

type iRadioVtbl struct {
	ole.IInspectableVtbl

	SetStateAsync      uintptr
	AddStateChanged    uintptr
	RemoveStateChanged uintptr
	GetState           uintptr
	GetName            uintptr
	GetKind            uintptr
}

func (v *iRadio) VTable() *iRadioVtbl {
	return (*iRadioVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iRadio) SetStateAsync(value RadioState) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetStateAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(value),                // in RadioState
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iRadio) AddStateChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddStateChanged,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iRadio) RemoveStateChanged(eventCookie foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveStateChanged,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(&eventCookie)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iRadio) GetState() (RadioState, error) {
	var out RadioState
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetState,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out RadioState
	)

	if hr != 0 {
		return RadioStateUnknown, ole.NewError(hr)
	}

	return out, nil
}

func (v *iRadio) GetName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iRadio) GetKind() (RadioKind, error) {
	var out RadioKind
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKind,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out RadioKind
	)

	if hr != 0 {
		return RadioKindOther, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiRadioStatics string = "5fb6a12e-67cb-46ae-aae9-65919f86eff4"
const SignatureiRadioStatics string = "{5fb6a12e-67cb-46ae-aae9-65919f86eff4}"

type iRadioStatics struct {
	ole.IInspectable
}

type iRadioStaticsVtbl struct {
	ole.IInspectableVtbl

	RadioGetRadiosAsync     uintptr
	RadioGetDeviceSelector  uintptr
	RadioFromIdAsync        uintptr
	RadioRequestAccessAsync uintptr
}

func (v *iRadioStatics) VTable() *iRadioStaticsVtbl {
	return (*iRadioStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func RadioGetRadiosAsync() (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Radios.Radio", ole.NewGUID(GUIDiRadioStatics))
	if err != nil {
		return nil, err
	}
	v := (*iRadioStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().RadioGetRadiosAsync,
		uintptr(unsafe.Pointer(v)),    // this (activation-factory instance method)
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func RadioGetDeviceSelector() (string, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Radios.Radio", ole.NewGUID(GUIDiRadioStatics))
	if err != nil {
		return "", err
	}
	v := (*iRadioStatics)(unsafe.Pointer(inspectable))

	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().RadioGetDeviceSelector,
		uintptr(unsafe.Pointer(v)),        // this (activation-factory instance method)
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func RadioFromIdAsync(deviceId string) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Radios.Radio", ole.NewGUID(GUIDiRadioStatics))
	if err != nil {
		return nil, err
	}
	v := (*iRadioStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	deviceIdHStr, err := ole.NewHString(deviceId)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().RadioFromIdAsync,
		uintptr(unsafe.Pointer(v)),    // this (activation-factory instance method)
		uintptr(deviceIdHStr),         // in string
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func RadioRequestAccessAsync() (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Radios.Radio", ole.NewGUID(GUIDiRadioStatics))
	if err != nil {
		return nil, err
	}
	v := (*iRadioStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().RadioRequestAccessAsync,
		uintptr(unsafe.Pointer(v)),    // this (activation-factory instance method)
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
