// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package radios

type RadioState int32

const SignatureRadioState string = "enum(Windows.Devices.Radios.RadioState;i4)"

const (
	RadioStateUnknown  RadioState = 0
	RadioStateOn       RadioState = 1
	RadioStateOff      RadioState = 2
	RadioStateDisabled RadioState = 3
)
