// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const GUIDIPropertyValue string = "4bd682dd-7554-40e9-9a9b-82654ede7e62"
const SignatureIPropertyValue string = "{4bd682dd-7554-40e9-9a9b-82654ede7e62}"

type IPropertyValue struct {
	ole.IInspectable
}

type IPropertyValueVtbl struct {
	ole.IInspectableVtbl

	GetType             uintptr
	GetIsNumericScalar  uintptr
	GetUInt8            uintptr
	GetInt16            uintptr
	GetUInt16           uintptr
	GetInt32            uintptr
	GetUInt32           uintptr
	GetInt64            uintptr
	GetUInt64           uintptr
	GetSingle           uintptr
	GetDouble           uintptr
	GetChar16           uintptr
	GetBoolean          uintptr
	GetString           uintptr
	GetGuid             uintptr
	GetDateTime         uintptr
	GetTimeSpan         uintptr
	GetPoint            uintptr
	GetSize             uintptr
	GetRect             uintptr
	GetUInt8Array       uintptr
	GetInt16Array       uintptr
	GetUInt16Array      uintptr
	GetInt32Array       uintptr
	GetUInt32Array      uintptr
	GetInt64Array       uintptr
	GetUInt64Array      uintptr
	GetSingleArray      uintptr
	GetDoubleArray      uintptr
	GetChar16Array      uintptr
	GetBooleanArray     uintptr
	GetStringArray      uintptr
	GetInspectableArray uintptr
	GetGuidArray        uintptr
	GetDateTimeArray    uintptr
	GetTimeSpanArray    uintptr
	GetPointArray       uintptr
	GetSizeArray        uintptr
	GetRectArray        uintptr
}

func (v *IPropertyValue) VTable() *IPropertyValueVtbl {
	return (*IPropertyValueVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IPropertyValue) GetInt32() (int32, error) {
	var out int32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInt32,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetBoolean() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetBoolean,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetString() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetString,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
